# Generated by Django 5.2.1 on 2025-05-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Funds'), ('WITHDRAW', 'Withdraw Funds'), ('TRANSFER', 'Transfer Funds'), ('RECEIVE', 'Receive Funds')], max_length=10),
        ),
    ]
