# Generated by Django 5.2.1 on 2025-05-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Funds'), ('WITHDRAW', 'Withdraw Funds'), ('TRANSFER', 'Transfer Funds'), ('RECEIVE', 'Receive Funds')], max_length=15),
        ),
    ]
